//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace T1.B1.WithholdingTax {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class CacheItemNames : global::System.Configuration.ApplicationSettingsBase {
        
        private static CacheItemNames defaultInstance = ((CacheItemNames)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new CacheItemNames())));
        
        public static CacheItemNames Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("cachebp001")]
        public string strBPFrom {
            get {
                return ((string)(this["strBPFrom"]));
            }
            set {
                this["strBPFrom"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("cachebp002")]
        public string strIBPTo {
            get {
                return ((string)(this["strIBPTo"]));
            }
            set {
                this["strIBPTo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("cachebp003")]
        public string strBPGroup {
            get {
                return ((string)(this["strBPGroup"]));
            }
            set {
                this["strBPGroup"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("cachebp004")]
        public string strBPType {
            get {
                return ((string)(this["strBPType"]));
            }
            set {
                this["strBPType"] = value;
            }
        }
    }
}
