//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace T1.B1.WithholdingTax {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class InteractionId : global::System.Configuration.ApplicationSettingsBase {
        
        private static InteractionId defaultInstance = ((InteractionId)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new InteractionId())));
        
        public static InteractionId Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("bybwhtm001")]
        public string mnuWHTMasterFormId {
            get {
                return ((string)(this["mnuWHTMasterFormId"]));
            }
            set {
                this["mnuWHTMasterFormId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("bybwhtf001")]
        public string frmWHTMasterFormId {
            get {
                return ((string)(this["frmWHTMasterFormId"]));
            }
            set {
                this["frmWHTMasterFormId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("bybwhtf001")]
        public string frmWHTMasterFormType {
            get {
                return ((string)(this["frmWHTMasterFormType"]));
            }
            set {
                this["frmWHTMasterFormType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("15616")]
        public string mnuWHTMasterParent {
            get {
                return ((string)(this["mnuWHTMasterParent"]));
            }
            set {
                this["mnuWHTMasterParent"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("bybrptm01")]
        public string mnuWHTReportId {
            get {
                return ((string)(this["mnuWHTReportId"]));
            }
            set {
                this["mnuWHTReportId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("bybwhtm01")]
        public string mnuWHTMainMenuId {
            get {
                return ((string)(this["mnuWHTMainMenuId"]));
            }
            set {
                this["mnuWHTMainMenuId"] = value;
            }
        }
    }
}
