//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace T1.B1.WithholdingTax {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class LocalizationStrings : global::System.Configuration.ApplicationSettingsBase {
        
        private static LocalizationStrings defaultInstance = ((LocalizationStrings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new LocalizationStrings())));
        
        public static LocalizationStrings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Retención por artículo")]
        public string mnuWHTMasterFormString {
            get {
                return ((string)(this["mnuWHTMasterFormString"]));
            }
            set {
                this["mnuWHTMasterFormString"] = value;
            }
        }
    }
}
