//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace T1.B1.WithholdingTax {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class MessageStrings : global::System.Configuration.ApplicationSettingsBase {
        
        private static MessageStrings defaultInstance = ((MessageStrings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new MessageStrings())));
        
        public static MessageStrings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Por favor seleccione al menos un criterio de selección.")]
        public string selectAnyValidationMessage {
            get {
                return ((string)(this["selectAnyValidationMessage"]));
            }
            set {
                this["selectAnyValidationMessage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Las cuentas contables y el código de transacción son campos obligatorios para el " +
            "registro, por favor seleccione los valores.")]
        public string selectTransactionMessage {
            get {
                return ((string)(this["selectTransactionMessage"]));
            }
            set {
                this["selectTransactionMessage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("El total del deterioro debe ser mayor a cero.")]
        public string transactionValueGreaterThanZero {
            get {
                return ((string)(this["transactionValueGreaterThanZero"]));
            }
            set {
                this["transactionValueGreaterThanZero"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("El deterioro se ha contabilizado con éxito. ")]
        public string impairmentDoneMessage {
            get {
                return ((string)(this["impairmentDoneMessage"]));
            }
            set {
                this["impairmentDoneMessage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Reportes")]
        public string mnuWHTReportDescription {
            get {
                return ((string)(this["mnuWHTReportDescription"]));
            }
            set {
                this["mnuWHTReportDescription"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Retenciones")]
        public string mnuWHTMainMenuDescription {
            get {
                return ((string)(this["mnuWHTMainMenuDescription"]));
            }
            set {
                this["mnuWHTMainMenuDescription"] = value;
            }
        }
    }
}
