//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace T1.B1.xxxProjects {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class MessageStrings : global::System.Configuration.ApplicationSettingsBase {
        
        private static MessageStrings defaultInstance = ((MessageStrings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new MessageStrings())));
        
        public static MessageStrings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Se produjo una excepción recuperando la lista de proyectos.")]
        public string nullProjectList {
            get {
                return ((string)(this["nullProjectList"]));
            }
            set {
                this["nullProjectList"] = value;
            }
        }
    }
}
