//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace T1.Classes.Queries {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class DBQueries : global::System.Configuration.ApplicationSettingsBase {
        
        private static DBQueries defaultInstance = ((DBQueries)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new DBQueries())));
        
        public static DBQueries Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("select [{0}] from [{1}] where Code = \'{2}\'")]
        public string getVersionControlSQL {
            get {
                return ((string)(this["getVersionControlSQL"]));
            }
            set {
                this["getVersionControlSQL"] = value;
            }
        }
    }
}
