//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace T1.B1.xxxBPImpairment.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class BPImpairment {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BPImpairment() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("T1.B1.xxxBPImpairment.Resources.BPImpairment", typeof(BPImpairment).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-16&quot;?&gt;
        ///&lt;Application&gt;
        ///  &lt;forms&gt;
        ///    &lt;action type=&quot;add&quot;&gt;
        ///      &lt;form appformnumber=&quot;-1&quot; FormType=&quot;-1&quot; type=&quot;0&quot; BorderStyle=&quot;0&quot; uid=&quot;&quot; title=&quot;Análisis de Deterioro de Cuentas&quot; visible=&quot;0&quot; default_button=&quot;&quot; pane=&quot;1&quot; color=&quot;0&quot; width=&quot;477&quot; height=&quot;217&quot; client_width=&quot;&quot; client_height=&quot;&quot; AutoManaged=&quot;0&quot; SupportedModes=&quot;15&quot; ObjectType=&quot;&quot; mode=&quot;1&quot;&gt;
        ///        &lt;datasources&gt;
        ///          &lt;DataTables /&gt;
        ///          &lt;dbdatasources&gt;
        ///            &lt;action type=&quot;add&quot; /&gt;
        ///          &lt;/dbdatasourc [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DBP001 {
            get {
                return ResourceManager.GetString("DBP001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-16&quot;?&gt;
        ///&lt;Application&gt;
        ///  &lt;forms&gt;
        ///    &lt;action type=&quot;add&quot;&gt;
        ///      &lt;form appformnumber=&quot;-1&quot; FormType=&quot;-1&quot; type=&quot;0&quot; BorderStyle=&quot;0&quot; uid=&quot;UBK000008&quot; title=&quot;Análisis de Deterioro de Cuentas&quot; visible=&quot;0&quot; default_button=&quot;&quot; pane=&quot;0&quot; color=&quot;0&quot; left=&quot;672&quot; top=&quot;206&quot; width=&quot;578&quot; height=&quot;616&quot; client_width=&quot;562&quot; client_height=&quot;577&quot; AutoManaged=&quot;0&quot; SupportedModes=&quot;15&quot; ObjectType=&quot;&quot; mode=&quot;1&quot;&gt;
        ///        &lt;datasources&gt;
        ///          &lt;DataTables&gt;
        ///            &lt;DataTable Uid=&quot;DT_BPI&quot;&gt;
        ///              [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DBP002 {
            get {
                return ResourceManager.GetString("DBP002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;Metadata&gt;
        ///  &lt;Tables&gt;
        ///    &lt;item name=&quot;SAPNFS&quot;&gt;
        ///      &lt;BOM&gt;
        ///        &lt;BO&gt;
        ///          &lt;AdmInfo&gt;
        ///            &lt;Object&gt;153&lt;/Object&gt;
        ///            &lt;Version&gt;2&lt;/Version&gt;
        ///          &lt;/AdmInfo&gt;
        ///          &lt;UserTablesMD&gt;
        ///            &lt;row&gt;
        ///              &lt;TableName&gt;SAPNFS&lt;/TableName&gt;
        ///              &lt;TableDescription&gt;SAPNFS&lt;/TableDescription&gt;
        ///              &lt;TableType&gt;bott_MasterData&lt;/TableType&gt;
        ///              &lt;Archivable&gt;tNO&lt;/Archivable&gt;
        ///            &lt;/row&gt;
        ///          &lt;/User [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MetadataCreation {
            get {
                return ResourceManager.GetString("MetadataCreation", resourceCulture);
            }
        }
    }
}
