//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace T1.B1.xxxBPImpairment.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class sqlQueries {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal sqlQueries() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("T1.B1.xxxBPImpairment.Resources.sqlQueries", typeof(sqlQueries).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OINV.
        /// </summary>
        internal static string BPTypeINV {
            get {
                return ResourceManager.GetString("BPTypeINV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OPOR.
        /// </summary>
        internal static string BPTypePUR {
            get {
                return ResourceManager.GetString("BPTypePUR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select
        ///T0.CardCode as &apos;Codigo&apos;,
        ///T0.CardName as &apos;Nombre&apos;,
        ///T0.DocEntry as &apos;Numero Documento&apos;,
        ///T0.DocDate  as &apos;Fecha Documento&apos;,
        ///T0.DocDueDate as &apos;Vencimiento&apos;,
        ///abs(DATEDIFF(day,GETDATE(),T0.DocDueDate)) as &apos;Edad&apos;,
        ///&apos;N&apos;as Checked, 
        ///T0.DocTotal as &apos;Doc. Total&apos;,
        ///T0.PaidToDate as &apos;Abono&apos;,
        ///T0.DocTotal - T0.PaidToDate as &apos;Deuda Total&apos;,
        ///0.0 as &apos;Indice&apos;,
        ///0.0 as &apos;Valor Presente&apos;,
        ///0.0 as &apos;Deterioro&apos;,
        ///100.0 as &apos;Porcentaje&apos;,
        ///0.0 as &apos;Total&apos;
        /// from {0} T0
        ///inner join OCRD on T0.CardCode = OCRD.CardCode
        ///inner [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string sql0001 {
            get {
                return ResourceManager.GetString("sql0001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and 
        ///T0.CardCode {0}= &apos;{1}&apos;.
        /// </summary>
        internal static string sql0002 {
            get {
                return ResourceManager.GetString("sql0002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and 
        ///T0.CardCode &lt;= &apos;{0}&apos;.
        /// </summary>
        internal static string sql0003 {
            get {
                return ResourceManager.GetString("sql0003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and
        ///OCRG.GroupCode = &apos;{0}&apos;
        ///.
        /// </summary>
        internal static string sql0004 {
            get {
                return ResourceManager.GetString("sql0004", resourceCulture);
            }
        }
    }
}
