//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace T1.B1.xxxBPImpairment {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class InteractionId : global::System.Configuration.ApplicationSettingsBase {
        
        private static InteractionId defaultInstance = ((InteractionId)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new InteractionId())));
        
        public static InteractionId Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("sapbp001")]
        public string mnuBPFilteringId {
            get {
                return ((string)(this["mnuBPFilteringId"]));
            }
            set {
                this["mnuBPFilteringId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("sapbp002")]
        public string frmBPFilteringFormId {
            get {
                return ((string)(this["frmBPFilteringFormId"]));
            }
            set {
                this["frmBPFilteringFormId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("sapbp003")]
        public string frmBPFilteringFormType {
            get {
                return ((string)(this["frmBPFilteringFormType"]));
            }
            set {
                this["frmBPFilteringFormType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("43536")]
        public string mnuBPFilteringParent {
            get {
                return ((string)(this["mnuBPFilteringParent"]));
            }
            set {
                this["mnuBPFilteringParent"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("sapbp004")]
        public string frmBPResultFormId {
            get {
                return ((string)(this["frmBPResultFormId"]));
            }
            set {
                this["frmBPResultFormId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("sapbp005")]
        public string frmBPResultFormType {
            get {
                return ((string)(this["frmBPResultFormType"]));
            }
            set {
                this["frmBPResultFormType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/Metadata/Tables/item")]
        public string mdTablePath {
            get {
                return ((string)(this["mdTablePath"]));
            }
            set {
                this["mdTablePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/Metadata/UserFields/item")]
        public string mdUserFieldsPath {
            get {
                return ((string)(this["mdUserFieldsPath"]));
            }
            set {
                this["mdUserFieldsPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/Metadata/UDO/item")]
        public string mdUDOPath {
            get {
                return ((string)(this["mdUDOPath"]));
            }
            set {
                this["mdUDOPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("13")]
        public string InvoiceObjectType {
            get {
                return ((string)(this["InvoiceObjectType"]));
            }
            set {
                this["InvoiceObjectType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("18")]
        public string PurchaseObjectType {
            get {
                return ((string)(this["PurchaseObjectType"]));
            }
            set {
                this["PurchaseObjectType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Item_16")]
        public string frmBPFilteringQueryButtonId {
            get {
                return ((string)(this["frmBPFilteringQueryButtonId"]));
            }
            set {
                this["frmBPFilteringQueryButtonId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Item_15")]
        public string frmBPImpairmentGridId {
            get {
                return ((string)(this["frmBPImpairmentGridId"]));
            }
            set {
                this["frmBPImpairmentGridId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Indice")]
        public string frmBPImpairmentColumnIndex {
            get {
                return ((string)(this["frmBPImpairmentColumnIndex"]));
            }
            set {
                this["frmBPImpairmentColumnIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Deterioro")]
        public string frmBPImpairmentColumnDeterioro {
            get {
                return ((string)(this["frmBPImpairmentColumnDeterioro"]));
            }
            set {
                this["frmBPImpairmentColumnDeterioro"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Porcentaje")]
        public string frmBPImpairmentColumnPercentage {
            get {
                return ((string)(this["frmBPImpairmentColumnPercentage"]));
            }
            set {
                this["frmBPImpairmentColumnPercentage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Item_1")]
        public string frmBPImpairmentButtonSumId {
            get {
                return ((string)(this["frmBPImpairmentButtonSumId"]));
            }
            set {
                this["frmBPImpairmentButtonSumId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Item_16")]
        public string frmBPImpairmentButtonContabId {
            get {
                return ((string)(this["frmBPImpairmentButtonContabId"]));
            }
            set {
                this["frmBPImpairmentButtonContabId"] = value;
            }
        }
    }
}
