//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace T1.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.5.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.1.0.0")]
        public string version {
            get {
                return ((string)(this["version"]));
            }
            set {
                this["version"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("@BYBT1")]
        public string versionControlSQLTable {
            get {
                return ((string)(this["versionControlSQLTable"]));
            }
            set {
                this["versionControlSQLTable"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/Metadata/Tables/item")]
        public string mdTablePath {
            get {
                return ((string)(this["mdTablePath"]));
            }
            set {
                this["mdTablePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/Metadata/UserFields/item")]
        public string mdUserFieldsPath {
            get {
                return ((string)(this["mdUserFieldsPath"]));
            }
            set {
                this["mdUserFieldsPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/Metadata/UDO/item")]
        public string mdUDOPath {
            get {
                return ((string)(this["mdUDOPath"]));
            }
            set {
                this["mdUDOPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("BYB T1")]
        public string AddOnName {
            get {
                return ((string)(this["AddOnName"]));
            }
            set {
                this["AddOnName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ControlXML")]
        public string VersionControlCacheName {
            get {
                return ((string)(this["VersionControlCacheName"]));
            }
            set {
                this["VersionControlCacheName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/CrystalReports/ReportType/Item")]
        public string crReportTypePath {
            get {
                return ((string)(this["crReportTypePath"]));
            }
            set {
                this["crReportTypePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("BYB")]
        public string ReportAuthor {
            get {
                return ((string)(this["ReportAuthor"]));
            }
            set {
                this["ReportAuthor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("./Report")]
        public string crReportPath {
            get {
                return ((string)(this["crReportPath"]));
            }
            set {
                this["crReportPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("BYBT1")]
        public string versionControlKey {
            get {
                return ((string)(this["versionControlKey"]));
            }
            set {
                this["versionControlKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("U_ControlXML")]
        public string versionControlField {
            get {
                return ((string)(this["versionControlField"]));
            }
            set {
                this["versionControlField"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("BYBT1")]
        public string versionControlB1Table {
            get {
                return ((string)(this["versionControlB1Table"]));
            }
            set {
                this["versionControlB1Table"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SAP Business One")]
        public string processWindowNameString {
            get {
                return ((string)(this["processWindowNameString"]));
            }
            set {
                this["processWindowNameString"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool showB1Message {
            get {
                return ((bool)(this["showB1Message"]));
            }
            set {
                this["showB1Message"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool cancelstrCode {
            get {
                return ((bool)(this["cancelstrCode"]));
            }
            set {
                this["cancelstrCode"] = value;
            }
        }
    }
}
