//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace T1.B1.xxxFSNotes.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class FSNotes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FSNotes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("T1.B1.xxxFSNotes.Resources.FSNotes", typeof(FSNotes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;CrystalReports&gt;
        ///  &lt;ReportType&gt;
        ///    &lt;Item name=&quot;FSNotes&quot; formId=&quot;SAP_FSN001&quot;&gt;
        ///      &lt;Report name=&quot;Example Note&quot; file=&quot;\B1\FSNotes\CR\ExampleNotesCR.rpt&quot;&gt;&lt;/Report&gt;
        ///      &lt;Report name=&quot;Custom Note&quot; file=&quot;\B1\FSNotes\CR\CustomNotesCR.rpt&quot;&gt;&lt;/Report&gt;
        ///      
        ///    &lt;/Item&gt;
        ///  &lt;/ReportType&gt;
        ///  
        ///&lt;/CrystalReports&gt;
        ///.
        /// </summary>
        internal static string CRDefinition {
            get {
                return ResourceManager.GetString("CRDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-16&quot;?&gt;
        ///&lt;Application&gt;
        ///  &lt;forms&gt;
        ///    &lt;action type=&quot;add&quot;&gt;
        ///      &lt;form appformnumber=&quot;-1&quot; FormType=&quot;-1&quot; type=&quot;0&quot; BorderStyle=&quot;0&quot; uid=&quot;&quot; title=&quot;/strTitle/&quot; visible=&quot;0&quot; default_button=&quot;&quot; pane=&quot;1&quot; color=&quot;0&quot; left=&quot;0&quot; top=&quot;0&quot; width=&quot;490&quot; height=&quot;374&quot; client_width=&quot;&quot; client_height=&quot;&quot; AutoManaged=&quot;0&quot; SupportedModes=&quot;15&quot; ObjectType=&quot;&quot; mode=&quot;1&quot;&gt;
        ///        &lt;datasources&gt;
        ///          &lt;DataTables /&gt;
        ///          &lt;dbdatasources&gt;
        ///            &lt;action type=&quot;add&quot; /&gt;
        ///          &lt;/dbdatasources&gt;
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FSN0001 {
            get {
                return ResourceManager.GetString("FSN0001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;Metadata&gt;
        ///  &lt;Tables&gt;
        ///    &lt;item name=&quot;SAPNFS&quot;&gt;
        ///      &lt;BOM&gt;
        ///        &lt;BO&gt;
        ///          &lt;AdmInfo&gt;
        ///            &lt;Object&gt;153&lt;/Object&gt;
        ///            &lt;Version&gt;2&lt;/Version&gt;
        ///          &lt;/AdmInfo&gt;
        ///          &lt;UserTablesMD&gt;
        ///            &lt;row&gt;
        ///              &lt;TableName&gt;SAPNFS&lt;/TableName&gt;
        ///              &lt;TableDescription&gt;SAPNFS&lt;/TableDescription&gt;
        ///              &lt;TableType&gt;bott_MasterData&lt;/TableType&gt;
        ///              &lt;Archivable&gt;tNO&lt;/Archivable&gt;
        ///            &lt;/row&gt;
        ///          &lt;/User [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MetadataCreation {
            get {
                return ResourceManager.GetString("MetadataCreation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\ansi\ansicpg1252\cocoartf1344\cocoasubrtf720
        ///{\fonttbl\f0\fnil\fcharset0 Calibri;}
        ///{\colortbl;\red255\green255\blue255;}
        ///\margl1440\margr1440\vieww16900\viewh14660\viewkind0
        ///\deftab720
        ///\pard\tx474\pardeftab720\ri3080\qj
        ///
        ///\f0\b\fs20 \cf0 Informaci\&apos;f3n\kerning1\expnd-5\expndtw-22
        /// \kerning1\expnd0\expndtw0 general
        ///\b0 \
        ///\pard\pardeftab720\ri3080\sb4
        ///
        ///\b \cf0 \
        ///\pard\tx2746\pardeftab720\ri3190\qj
        ///
        ///\b0 \cf0 \kerning1\expnd-1\expndtw-1
        ///XYZ\kerning1\expnd6\expndtw30
        /// \kerning1\expnd-1\expndtw-1
        ///(Controlad [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Nota_1 {
            get {
                return ResourceManager.GetString("Nota_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\ansi\ansicpg1252\cocoartf1344\cocoasubrtf720
        ///{\fonttbl\f0\fnil\fcharset0 Calibri;}
        ///{\colortbl;\red255\green255\blue255;\red191\green191\blue191;}
        ///{\info
        ///{\title Microsoft Word - ES IFRS for SMEs_IG_ENVIADO_IASB_final _2_.doc}
        ///{\author mzaccarelli}}\paperw8680\paperh14060\margl1200\margr1200\margb280\margt1340\viewkind1\viewscale150
        ///\deftab720
        ///\pard\pardeftab720\li167\ri0\qj
        ///
        ///\f0\b\fs22 \cf0 Deudores\kerning1\expnd-2\expndtw-8
        /// \kerning1\expnd0\expndtw0 comerciales\kerning1\expnd-2\expndtw-7
        /// \kerning [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Nota_10 {
            get {
                return ResourceManager.GetString("Nota_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\ansi\ansicpg1252\cocoartf1344\cocoasubrtf720
        ///{\fonttbl\f0\fnil\fcharset0 Calibri;\f1\fswiss\fcharset0 ArialMT;}
        ///{\colortbl;\red255\green255\blue255;\red191\green191\blue191;}
        ///{\info
        ///{\title Microsoft Word - ES IFRS for SMEs_IG_ENVIADO_IASB_final _2_.doc}
        ///{\author mzaccarelli}}\paperw8680\paperh14060\margl1200\margr1200\margb280\margt1340\viewkind1\viewscale150
        ///\deftab720
        ///\pard\pardeftab720\ri0\sb3
        ///
        ///\f0\b\fs17 \cf0 \
        ///\pard\pardeftab720\li55\ri0
        ///
        ///\f1\fs22 \cf0 Inventarios
        ///\f0\b0 \
        ///
        ///\itap1\trowd \taflag [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Nota_11 {
            get {
                return ResourceManager.GetString("Nota_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\ansi\ansicpg1252\cocoartf1344\cocoasubrtf720
        ///{\fonttbl\f0\fnil\fcharset0 Calibri;}
        ///{\colortbl;\red255\green255\blue255;\red191\green191\blue191;}
        ///{\info
        ///{\title Microsoft Word - ES IFRS for SMEs_IG_ENVIADO_IASB_final _2_.doc}
        ///{\author mzaccarelli}}\paperw8680\paperh14060\margl1200\margr1200\margb280\margt1340\viewkind1\viewscale150
        ///\deftab720
        ///\pard\tx528\pardeftab720\ri0\sb71
        ///
        ///\f0\b\fs22 \cf0 Inversiones\kerning1\expnd-3\expndtw-14
        /// \kerning1\expnd0\expndtw0 en\kerning1\expnd-3\expndtw-13
        /// \kerning1\ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Nota_12 {
            get {
                return ResourceManager.GetString("Nota_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\ansi\ansicpg1252\cocoartf1344\cocoasubrtf720
        ///{\fonttbl\f0\fnil\fcharset0 Calibri;}
        ///{\colortbl;\red255\green255\blue255;\red191\green191\blue191;}
        ///{\info
        ///{\title Microsoft Word - ES IFRS for SMEs_IG_ENVIADO_IASB_final _2_.doc}
        ///{\author mzaccarelli}}\paperw8680\paperh14060\margl1200\margr1200\margb280\margt1340\viewkind1\viewscale150
        ///\deftab720
        ///\pard\tx534\pardeftab720\ri43\sb71
        ///
        ///\f0\b\fs22 \cf0 Propiedades,\kerning1\expnd-2\expndtw-10
        /// \kerning1\expnd0\expndtw0 planta\kerning1\expnd-2\expndtw-9
        /// \kern [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Nota_13 {
            get {
                return ResourceManager.GetString("Nota_13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\ansi\ansicpg1252\cocoartf1344\cocoasubrtf720
        ///{\fonttbl\f0\fnil\fcharset0 Calibri;}
        ///{\colortbl;\red255\green255\blue255;}
        ///{\info
        ///{\title Microsoft Word - ES IFRS for SMEs_IG_ENVIADO_IASB_final _2_.doc}
        ///{\author mzaccarelli}}\paperw8680\paperh14060\margl1200\margr1200\margb280\margt1340\viewkind1\viewscale150
        ///\deftab720
        ///\pard\tx468\pardeftab720\ri0
        ///
        ///\f0\b\fs22 \cf0 Activos\kerning1\expnd-4\expndtw-20
        /// \kerning1\expnd0\expndtw0 intangibles
        ///\b0 \
        ///\pard\pardeftab720\ri0\sb3
        ///
        ///\b\fs17 \cf0 \
        ///\pard\pardeftab [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Nota_14 {
            get {
                return ResourceManager.GetString("Nota_14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\ansi\ansicpg1252\cocoartf1344\cocoasubrtf720
        ///{\fonttbl\f0\fswiss\fcharset0 ArialMT;\f1\fnil\fcharset0 Calibri;\f2\froman\fcharset0 TimesNewRomanPSMT;
        ///}
        ///{\colortbl;\red255\green255\blue255;\red191\green191\blue191;}
        ///{\*\listtable{\list\listtemplateid1\listhybrid{\listlevel\levelnfc0\levelnfcn0\leveljc0\leveljcn0\levelfollow0\levelstartat12\levelspace360\levelindent0{\*\levelmarker \{decimal\}.}{\leveltext\leveltemplateid1\&apos;02\&apos;00.;}{\levelnumbers\&apos;01;}\fi-360\li720\lin720 }{\listname ;}\listid1}
        ///{\lis [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Nota_15 {
            get {
                return ResourceManager.GetString("Nota_15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\ansi\ansicpg1252\cocoartf1344\cocoasubrtf720
        ///{\fonttbl\f0\fnil\fcharset0 Calibri;}
        ///{\colortbl;\red255\green255\blue255;\red191\green191\blue191;}
        ///{\info
        ///{\title Microsoft Word - ES IFRS for SMEs_IG_ENVIADO_IASB_final _2_.doc}
        ///{\author mzaccarelli}}\paperw8680\paperh14060\margl1200\margr1200\margb280\margt1340\viewkind1\viewscale150
        ///\deftab720
        ///\pard\pardeftab720\ri0\sb3
        ///
        ///\f0\fs17 \cf0 \
        ///\pard\tx4306\tx6040\pardeftab720\li118\ri0
        ///
        ///\b\fs22 \cf0 Sobregiros\kerning1\expnd-2\expndtw-9
        /// \kerning1\expnd0\exp [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Nota_16 {
            get {
                return ResourceManager.GetString("Nota_16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\ansi\ansicpg1252\cocoartf1344\cocoasubrtf720
        ///{\fonttbl\f0\fnil\fcharset0 Calibri;}
        ///{\colortbl;\red255\green255\blue255;}
        ///{\info
        ///{\title Microsoft Word - ES IFRS for SMEs_IG_ENVIADO_IASB_final _2_.doc}
        ///{\author mzaccarelli}}\paperw8680\paperh14060\margl1200\margr1200\margb280\margt1340\viewkind1\viewscale150
        ///\deftab720
        ///\pard\tx534\pardeftab720\ri0\qj
        ///
        ///\f0\b\fs22 \cf0 Acreedores\kerning1\expnd-5\expndtw-24
        /// \kerning1\expnd0\expndtw0 comerciales
        ///\b0 \
        ///\pard\pardeftab720\ri0\sb4
        ///
        ///\b\fs17 \cf0 \
        ///\pard\par [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Nota_17 {
            get {
                return ResourceManager.GetString("Nota_17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\ansi\ansicpg1252\cocoartf1344\cocoasubrtf720
        ///{\fonttbl\f0\fnil\fcharset0 Calibri;}
        ///{\colortbl;\red255\green255\blue255;}
        ///{\info
        ///{\title Microsoft Word - ES IFRS for SMEs_IG_ENVIADO_IASB_final _2_.doc}
        ///{\author mzaccarelli}}\paperw8680\paperh14060\margl1200\margr1200\margb280\margt1340\viewkind1\viewscale150
        ///\deftab720
        ///\pard\tx528\pardeftab720\li-193\ri0
        ///
        ///\f0\b\fs22 \cf0 Provisi\&apos;f3n\kerning1\expnd-3\expndtw-11
        /// \kerning1\expnd0\expndtw0 para\kerning1\expnd-2\expndtw-10
        /// \kerning1\expnd0\expndtw0 obli [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Nota_18 {
            get {
                return ResourceManager.GetString("Nota_18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\ansi\ansicpg1252\cocoartf1344\cocoasubrtf720
        ///{\fonttbl\f0\fnil\fcharset0 Calibri;}
        ///{\colortbl;\red255\green255\blue255;\red191\green191\blue191;}
        ///{\info
        ///{\title Microsoft Word - ES IFRS for SMEs_IG_ENVIADO_IASB_final _2_.doc}
        ///{\author mzaccarelli}}\paperw8680\paperh14060\margl1200\margr1200\margb280\margt1340\viewkind1\viewscale150
        ///\deftab720
        ///\pard\tx528\pardeftab720\li134\ri229
        ///
        ///\f0\b\fs22 \cf0 Obligaci\&apos;f3n\kerning1\expnd-2\expndtw-8
        /// \kerning1\expnd0\expndtw0 por\kerning1\expnd-2\expndtw-7
        /// \kerni [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Nota_19 {
            get {
                return ResourceManager.GetString("Nota_19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\ansi\ansicpg1252\cocoartf1344\cocoasubrtf720
        ///{\fonttbl\f0\fnil\fcharset0 Calibri;}
        ///{\colortbl;\red255\green255\blue255;}
        ///\margl1440\margr1440\vieww10800\viewh8400\viewkind0
        ///\deftab720
        ///\pard\tx474\pardeftab720\ri3080\qj
        ///
        ///\f0\b\fs22 \cf0 Bases\kerning1\expnd-2\expndtw-9
        /// \kerning1\expnd0\expndtw0 de\kerning1\expnd-2\expndtw-8
        /// \kerning1\expnd0\expndtw0 elaboraci\&apos;f3n\kerning1\expnd-2\expndtw-8
        /// \kerning1\expnd0\expndtw0 y\kerning1\expnd-2\expndtw-9
        /// \kerning1\expnd0\expndtw0 pol\&apos;edticas\kerning1\expnd [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Nota_2 {
            get {
                return ResourceManager.GetString("Nota_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\ansi\ansicpg1252\cocoartf1344\cocoasubrtf720
        ///{\fonttbl\f0\fnil\fcharset0 Calibri;}
        ///{\colortbl;\red255\green255\blue255;}
        ///{\info
        ///{\title Microsoft Word - ES IFRS for SMEs_IG_ENVIADO_IASB_final _2_.doc}
        ///{\author mzaccarelli}}\paperw8680\paperh14060\margl1200\margr1200\margb280\margt1340\viewkind1\viewscale150
        ///\deftab720
        ///\pard\tx528\pardeftab720\ri0\sb71\qj
        ///
        ///\f0\b\fs22 \cf0 Obligaciones\kerning1\expnd-4\expndtw-17
        /// \kerning1\expnd0\expndtw0 por\kerning1\expnd-3\expndtw-15
        /// \kerning1\expnd0\expndtw0 arre [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Nota_20 {
            get {
                return ResourceManager.GetString("Nota_20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\ansi\ansicpg1252\cocoartf1344\cocoasubrtf720
        ///{\fonttbl\f0\fnil\fcharset0 Calibri;}
        ///{\colortbl;\red255\green255\blue255;\red191\green191\blue191;}
        ///{\info
        ///{\title Microsoft Word - ES IFRS for SMEs_IG_ENVIADO_IASB_final _2_.doc}
        ///{\author mzaccarelli}}\paperw8680\paperh14060\margl1200\margr1200\margb280\margt1340\viewkind1\viewscale150
        ///\deftab720
        ///\pard\tx534\pardeftab720\li134\ri0\sb308
        ///
        ///\f0\b\fs22 \cf0 Compromisos\kerning1\expnd-4\expndtw-16
        /// \kerning1\expnd0\expndtw0 por\kerning1\expnd-3\expndtw-15
        /// \k [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Nota_21 {
            get {
                return ResourceManager.GetString("Nota_21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\ansi\ansicpg1252\cocoartf1344\cocoasubrtf720
        ///{\fonttbl\f0\fnil\fcharset0 Calibri;}
        ///{\colortbl;\red255\green255\blue255;}
        ///{\info
        ///{\title Microsoft Word - ES IFRS for SMEs_IG_ENVIADO_IASB_final _2_.doc}
        ///{\author mzaccarelli}}\paperw8680\paperh14060\margl1200\margr1200\margb280\margt1340\viewkind1\viewscale150
        ///\deftab720
        ///\pard\tx534\pardeftab720\ri0\sb71\qj
        ///
        ///\f0\b\fs20 \cf0 Capital\kerning1\expnd-2\expndtw-10
        /// \kerning1\expnd0\expndtw0 en\kerning1\expnd-2\expndtw-10
        /// \kerning1\expnd0\expndtw0 acciones
        ///\ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Nota_22 {
            get {
                return ResourceManager.GetString("Nota_22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\ansi\ansicpg1252\cocoartf1344\cocoasubrtf720
        ///{\fonttbl\f0\fnil\fcharset0 Calibri;}
        ///{\colortbl;\red255\green255\blue255;}
        ///{\info
        ///{\title Microsoft Word - ES IFRS for SMEs_IG_ENVIADO_IASB_final _2_.doc}
        ///{\author mzaccarelli}}\paperw8680\paperh14060\margl1200\margr1200\margb280\margt1340\viewkind1\viewscale150
        ///\deftab720
        ///\pard\tx528\pardeftab720\ri0
        ///
        ///\f0\b\fs22 \cf0 Efectivo\kerning1\expnd-2\expndtw-8
        /// \kerning1\expnd0\expndtw0 y\kerning1\expnd-3\expndtw-11
        /// \kerning1\expnd0\expndtw0 equivalentes\kernin [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Nota_23 {
            get {
                return ResourceManager.GetString("Nota_23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\ansi\ansicpg1252\cocoartf1344\cocoasubrtf720
        ///{\fonttbl\f0\fnil\fcharset0 Calibri;}
        ///{\colortbl;\red255\green255\blue255;}
        ///{\info
        ///{\title Microsoft Word - ES IFRS for SMEs_IG_ENVIADO_IASB_final _2_.doc}
        ///{\author mzaccarelli}}\paperw8680\paperh14060\margl1200\margr1200\margb280\margt1340\viewkind1\viewscale150
        ///\deftab720
        ///\pard\tx528\pardeftab720\li134\ri0\sb71\qj
        ///
        ///\f0\b\fs22 \cf0 Pasivos\kerning1\expnd-5\expndtw-22
        /// \kerning1\expnd0\expndtw0 contingentes
        ///\b0 \
        ///\pard\pardeftab720\ri0\sb3
        ///
        ///\b\fs17 \cf0 \
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Nota_24 {
            get {
                return ResourceManager.GetString("Nota_24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\ansi\ansicpg1252\cocoartf1344\cocoasubrtf720
        ///{\fonttbl\f0\fnil\fcharset0 Calibri;}
        ///{\colortbl;\red255\green255\blue255;}
        ///{\info
        ///{\title Microsoft Word - ES IFRS for SMEs_IG_ENVIADO_IASB_final _2_.doc}
        ///{\author mzaccarelli}}\paperw8680\paperh14060\margl1200\margr1200\margb280\margt1340\viewkind1\viewscale150
        ///\deftab720
        ///\pard\tx528\pardeftab720\ri0
        ///
        ///\f0\b\fs20 \cf0 Hechos\kerning1\expnd-2\expndtw-7
        /// \kerning1\expnd0\expndtw0 ocurridos\kerning1\expnd-2\expndtw-8
        /// \kerning1\expnd0\expndtw0 despu\&apos;e9s\ker [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Nota_25 {
            get {
                return ResourceManager.GetString("Nota_25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\ansi\ansicpg1252\cocoartf1344\cocoasubrtf720
        ///{\fonttbl\f0\froman\fcharset0 TimesNewRomanPSMT;\f1\fnil\fcharset0 Calibri;}
        ///{\colortbl;\red255\green255\blue255;\red191\green191\blue191;}
        ///{\info
        ///{\title Microsoft Word - ES IFRS for SMEs_IG_ENVIADO_IASB_final _2_.doc}
        ///{\author mzaccarelli}}\paperw8680\paperh14060\margl1200\margr1200\margb280\margt1340\viewkind1\viewscale150
        ///\deftab720
        ///\pard\pardeftab720\ri0\sb5
        ///
        ///\f0\fs17 \cf0 \
        ///\pard\pardeftab720\li167\ri117\qj
        ///
        ///\fs19 \cf0 \
        ///\pard\pardeftab720\ri0\sb5
        ///
        ///\ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Nota_26 {
            get {
                return ResourceManager.GetString("Nota_26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\ansi\ansicpg1252\cocoartf1344\cocoasubrtf720
        ///{\fonttbl\f0\fswiss\fcharset0 ArialMT;\f1\froman\fcharset0 TimesNewRomanPSMT;\f2\fnil\fcharset0 Calibri;
        ///}
        ///{\colortbl;\red255\green255\blue255;}
        ///\paperw8680\paperh14060\margl1020\margr460\margb280\margt760\vieww8980\viewh14360\viewkind1\viewscale150
        ///\deftab720
        ///\pard\tx474\pardeftab720\ri0\sb71
        ///
        ///\f0\b\fs22 \cf0 Aprobaci\&apos;f3n\kerning1\expnd-2\expndtw-9
        /// \kerning1\expnd0\expndtw0 de\kerning1\expnd-2\expndtw-10
        /// \kerning1\expnd0\expndtw0 los\kerning1\expnd-2\e [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Nota_27 {
            get {
                return ResourceManager.GetString("Nota_27", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\ansi\ansicpg1252\cocoartf1344\cocoasubrtf720
        ///{\fonttbl\f0\fnil\fcharset0 Calibri;}
        ///{\colortbl;\red255\green255\blue255;}
        ///{\info
        ///{\title Microsoft Word - ES IFRS for SMEs_IG_ENVIADO_IASB_final _2_.doc}
        ///{\author mzaccarelli}}\paperw8680\paperh14060\margl1200\margr1200\margb280\margt1340\viewkind1\viewscale150
        ///\deftab720
        ///\pard\tx468\pardeftab720\ri0\qj
        ///
        ///\f0\b\fs22 \cf0 Supuestos\kerning1\expnd-2\expndtw-8
        /// \kerning1\expnd0\expndtw0 clave\kerning1\expnd-2\expndtw-7
        /// \kerning1\expnd0\expndtw0 de\kerning1\ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Nota_3 {
            get {
                return ResourceManager.GetString("Nota_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\ansi\ansicpg1252\cocoartf1344\cocoasubrtf720
        ///{\fonttbl\f0\fnil\fcharset0 Calibri;}
        ///{\colortbl;\red255\green255\blue255;}
        ///{\info
        ///{\title Microsoft Word - ES IFRS for SMEs_IG_ENVIADO_IASB_final _2_.doc}
        ///{\author mzaccarelli}}\paperw8680\paperh14060\margl1200\margr1200\margb280\margt1340\viewkind1\viewscale150
        ///\deftab720
        ///\pard\tx468\pardeftab720\ri0\qj
        ///
        ///\f0\b\fs20 \cf0 Restricci\&apos;f3n\kerning1\expnd-2\expndtw-8
        /// \kerning1\expnd0\expndtw0 al\kerning1\expnd-2\expndtw-8
        /// \kerning1\expnd0\expndtw0 pago\kerni [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Nota_4 {
            get {
                return ResourceManager.GetString("Nota_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\ansi\ansicpg1252\cocoartf1344\cocoasubrtf720
        ///{\fonttbl\f0\fnil\fcharset0 Calibri;}
        ///{\colortbl;\red255\green255\blue255;\red191\green191\blue191;}
        ///{\info
        ///{\title Microsoft Word - ES IFRS for SMEs_IG_ENVIADO_IASB_final _2_.doc}
        ///{\author mzaccarelli}}\paperw8680\paperh14060\margl1200\margr1200\margb280\margt1340\viewkind1\viewscale150
        ///\deftab720
        ///
        ///\itap1\trowd \taflags1 \trgaph108\trleft-108 \trbrdrt\brdrnil \trbrdrl\brdrnil \trbrdrr\brdrnil 
        ///\clvertalt \clshdrawnil \clwWidth4643\clftsWidth3 \clbrdrt\brd [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Nota_5 {
            get {
                return ResourceManager.GetString("Nota_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\ansi\ansicpg1252\cocoartf1344\cocoasubrtf720
        ///{\fonttbl\f0\fnil\fcharset0 Calibri;}
        ///{\colortbl;\red255\green255\blue255;}
        ///{\info
        ///{\title Microsoft Word - ES IFRS for SMEs_IG_ENVIADO_IASB_final _2_.doc}
        ///{\author mzaccarelli}}\paperw8680\paperh14060\margl1200\margr1200\margb280\margt1340\viewkind1\viewscale150
        ///\deftab720
        ///\pard\pardeftab720\ri0
        ///
        ///\f0\b\fs20 \cf0 Otros\kerning1\expnd-1\expndtw-5
        /// \kerning1\expnd0\expndtw0 ingresos
        ///\b0 \
        ///\pard\pardeftab720\ri129\sb103\qj
        ///\cf0 \kerning1\expnd-1\expndtw-1
        ///Otr [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Nota_6 {
            get {
                return ResourceManager.GetString("Nota_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\ansi\ansicpg1252\cocoartf1344\cocoasubrtf720
        ///{\fonttbl\f0\fnil\fcharset0 Calibri;}
        ///{\colortbl;\red255\green255\blue255;}
        ///{\info
        ///{\title Microsoft Word - ES IFRS for SMEs_IG_ENVIADO_IASB_final _2_.doc}
        ///{\author mzaccarelli}}\paperw8680\paperh14060\margl1200\margr1200\margb280\margt1340\viewkind1\viewscale150
        ///\deftab720
        ///\pard\tx534\pardeftab720\li134\ri0\qj
        ///
        ///\f0\b\fs22 \cf0 Costos\kerning1\expnd-4\expndtw-20
        /// \kerning1\expnd0\expndtw0 financieros
        ///\b0 \
        ///\pard\pardeftab720\ri0\sb1
        ///
        ///\b\fs23 \cf0 \
        ///\pard\t [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Nota_7 {
            get {
                return ResourceManager.GetString("Nota_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\ansi\ansicpg1252\cocoartf1344\cocoasubrtf720
        ///{\fonttbl\f0\fnil\fcharset0 Calibri;}
        ///{\colortbl;\red255\green255\blue255;}
        ///{\info
        ///{\title Microsoft Word - ES IFRS for SMEs_IG_ENVIADO_IASB_final _2_.doc}
        ///{\author mzaccarelli}}\paperw8680\paperh14060\margl1200\margr1200\margb280\margt1340\viewkind1\viewscale150
        ///\deftab720
        ///\pard\tx534\pardeftab720\li134\ri0\sb71
        ///
        ///\f0\b\fs22 \cf0 Ganancia\kerning1\expnd-3\expndtw-11
        /// \kerning1\expnd0\expndtw0 antes\kerning1\expnd-2\expndtw-10
        /// \kerning1\expnd0\expndtw0 de\ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Nota_8 {
            get {
                return ResourceManager.GetString("Nota_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\ansi\ansicpg1252\cocoartf1344\cocoasubrtf720
        ///{\fonttbl\f0\fnil\fcharset0 Calibri;}
        ///{\colortbl;\red255\green255\blue255;\red191\green191\blue191;}
        ///{\info
        ///{\title Microsoft Word - ES IFRS for SMEs_IG_ENVIADO_IASB_final _2_.doc}
        ///{\author mzaccarelli}}\paperw8680\paperh14060\margl1200\margr1200\margb280\margt1340\viewkind1\viewscale150
        ///\deftab720
        ///
        ///\itap1\trowd \taflags1 \trgaph108\trleft-108 \trwWidth7056\trftsWidth3 \trbrdrt\brdrnil \trbrdrl\brdrnil \trbrdrr\brdrnil 
        ///\clvertalt \clshdrawnil \clwWidth457 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Nota_9 {
            get {
                return ResourceManager.GetString("Nota_9", resourceCulture);
            }
        }
    }
}
