//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace T1.B1.xxxInventoryImpairment {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class CacheItemNames : global::System.Configuration.ApplicationSettingsBase {
        
        private static CacheItemNames defaultInstance = ((CacheItemNames)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new CacheItemNames())));
        
        public static CacheItemNames Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("cacheII001")]
        public string strItemFrom {
            get {
                return ((string)(this["strItemFrom"]));
            }
            set {
                this["strItemFrom"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("cacheII002")]
        public string strItemTo {
            get {
                return ((string)(this["strItemTo"]));
            }
            set {
                this["strItemTo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("cacheII003")]
        public string strItemGroup {
            get {
                return ((string)(this["strItemGroup"]));
            }
            set {
                this["strItemGroup"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("cacheII004")]
        public string strWarehouseCodeFrom {
            get {
                return ((string)(this["strWarehouseCodeFrom"]));
            }
            set {
                this["strWarehouseCodeFrom"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("caheII005")]
        public string strWarehoseCodeTo {
            get {
                return ((string)(this["strWarehoseCodeTo"]));
            }
            set {
                this["strWarehoseCodeTo"] = value;
            }
        }
    }
}
