//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace T1.B1.xxxInventoryImpairment {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class InteractionId : global::System.Configuration.ApplicationSettingsBase {
        
        private static InteractionId defaultInstance = ((InteractionId)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new InteractionId())));
        
        public static InteractionId Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("sapII001")]
        public string mnuItemsFilteringId {
            get {
                return ((string)(this["mnuItemsFilteringId"]));
            }
            set {
                this["mnuItemsFilteringId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("sapII002")]
        public string frmItemFilteringFormId {
            get {
                return ((string)(this["frmItemFilteringFormId"]));
            }
            set {
                this["frmItemFilteringFormId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("sapII003")]
        public string frmItemFilteringFormType {
            get {
                return ((string)(this["frmItemFilteringFormType"]));
            }
            set {
                this["frmItemFilteringFormType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1760")]
        public string mnuItemsFilteringParent {
            get {
                return ((string)(this["mnuItemsFilteringParent"]));
            }
            set {
                this["mnuItemsFilteringParent"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("sapII004")]
        public string frmItemResultFormId {
            get {
                return ((string)(this["frmItemResultFormId"]));
            }
            set {
                this["frmItemResultFormId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("sapII005")]
        public string frmItemResultFormType {
            get {
                return ((string)(this["frmItemResultFormType"]));
            }
            set {
                this["frmItemResultFormType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Item_1")]
        public string frmEditItemFromId {
            get {
                return ((string)(this["frmEditItemFromId"]));
            }
            set {
                this["frmEditItemFromId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Item_4")]
        public string frmEditItemToId {
            get {
                return ((string)(this["frmEditItemToId"]));
            }
            set {
                this["frmEditItemToId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Item_24")]
        public string frmEditItemGroupId {
            get {
                return ((string)(this["frmEditItemGroupId"]));
            }
            set {
                this["frmEditItemGroupId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Item_8")]
        public string frmEditWarehouseFromId {
            get {
                return ((string)(this["frmEditWarehouseFromId"]));
            }
            set {
                this["frmEditWarehouseFromId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Item_11")]
        public string frmEditWarehouseToId {
            get {
                return ((string)(this["frmEditWarehouseToId"]));
            }
            set {
                this["frmEditWarehouseToId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Item_16")]
        public string frmQueryButtonId {
            get {
                return ((string)(this["frmQueryButtonId"]));
            }
            set {
                this["frmQueryButtonId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Item_10")]
        public string frmCmbInvAcctId {
            get {
                return ((string)(this["frmCmbInvAcctId"]));
            }
            set {
                this["frmCmbInvAcctId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Item_11")]
        public string frmCmbImpAccId {
            get {
                return ((string)(this["frmCmbImpAccId"]));
            }
            set {
                this["frmCmbImpAccId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Item_15")]
        public string frmGridResultId {
            get {
                return ((string)(this["frmGridResultId"]));
            }
            set {
                this["frmGridResultId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Det. x Art.")]
        public string frmColumnDetId {
            get {
                return ((string)(this["frmColumnDetId"]));
            }
            set {
                this["frmColumnDetId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Item_1")]
        public string frmButtonSum {
            get {
                return ((string)(this["frmButtonSum"]));
            }
            set {
                this["frmButtonSum"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Item_16")]
        public string frmButtonCont {
            get {
                return ((string)(this["frmButtonCont"]));
            }
            set {
                this["frmButtonCont"] = value;
            }
        }
    }
}
