//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace T1.B1.WithholdingTax.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class dbQueries {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal dbQueries() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("T1.B1.WithholdingTax.Resources.dbQueries", typeof(dbQueries).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select U_DebitAcct, U_CreditAccount, U_Percent, [@BYB_T1SWT100].Code from 
        ///[@BYB_T1SWT100] 
        ///inner join [@BYB_T1SWT101] on [@BYB_T1SWT100].Code = [@BYB_T1SWT101].Code
        ///
        ///where U_Enabled=&apos;Y&apos; and [@BYB_T1SWT101].U_CardCode = &apos;[--CardCode--]&apos; and [@BYB_T1SWT100].Code=&apos;[--SWTCode--]&apos;.
        /// </summary>
        internal static string sqlGetActiveCodesSWTForBP {
            get {
                return ResourceManager.GetString("sqlGetActiveCodesSWTForBP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select CardCode, CardName from OCRD where CardType=&apos;C&apos;.
        /// </summary>
        internal static string sqlGetAllClients {
            get {
                return ResourceManager.GetString("sqlGetAllClients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select DocEntry, &apos;13&apos; as &quot;DocType&quot; 
        ///from
        ///OINV
        ///where DocEntry not in 
        ///( select U_DocEntry from [@BYB_T1WHT400] where U_DocType = &apos;13&apos;)
        ///
        ///union all
        ///select DocEntry, &apos;18&apos; as &quot;DocType&quot;
        ///from
        ///OPCH
        ///where DocEntry not in 
        ///( select U_DocEntry from [@BYB_T1WHT400] where U_DocType = &apos;18&apos;).
        /// </summary>
        internal static string sqlGetAllDocsWithWTInconsistences {
            get {
                return ResourceManager.GetString("sqlGetAllDocsWithWTInconsistences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select sum(Total) as &quot;Total&quot;
        ///from
        ///(
        ///select count(DocEntry)  as &quot;Total&quot;
        ///from
        ///OINV
        ///where DocEntry not in 
        ///( select U_DocEntry from [@BYB_T1WHT400] where U_DocType = &apos;13&apos;)
        ///
        ///union all
        ///select count(DocEntry)  as &quot;Total&quot;
        ///from
        ///OPCH
        ///where DocEntry not in 
        ///( select U_DocEntry from [@BYB_T1WHT400] where U_DocType = &apos;18&apos;)
        ///
        ///) as R.
        /// </summary>
        internal static string sqlGetAllWTInconsistences {
            get {
                return ResourceManager.GetString("sqlGetAllWTInconsistences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT 
        ///[U_Operation] as [Operación]
        ///	,OINV.[DocNum]
        ///	,[U_DocEntry]
        ///    ,[U_Type] as [Tipo]
        ///      ,[U_Source] as [Origen]
        ///      ,[U_Code] as [Código]
        ///      ,[U_Percent] as [Porcentaje]
        ///      ,[U_BaseAmnt] as [Base]
        ///      ,[U_Value] as [Valor]
        ///      ,[U_JE] as [Asiento]
        ///  FROM [@BYB_T1WHT401]
        ///  INNER JOIN [@BYB_T1WHT400] on [@BYB_T1WHT401].DocEntry = [@BYB_T1WHT400].DocEntry
        ///  INNER JOIN OINV on OINV.DocEntry = [@BYB_T1WHT400].[U_DocEntry]
        ///  where OINV.DocEntry = [--DocEntry--] and [@BYB_T1WHT4 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string sqlGetCurrentInfoFromUDO {
            get {
                return ResourceManager.GetString("sqlGetCurrentInfoFromUDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select
        ///&apos;CON&apos; as &apos;Origen&apos;
        ///,&apos;&apos; as &apos;Linea&apos;
        ///,&apos;&apos; as &apos;Codigo Retencion&apos;
        ///,0 as &apos;Porcentaje Retencion&apos;
        ///,TaxCode as &apos;Codigo IVA&apos;
        ///,VatPrcnt as &apos;Porcentaje IVA&apos;
        ///,sum(LineTotal - vatsum) as &apos;Base&apos;
        ///,sum(VatSum) as &apos;Total&apos;
        ///,&apos;&apos; as &apos;Detalle&apos;
        ///from inv1 where DocEntry=[--DocEntry--]
        ///group by DocEntry, TaxCode, VatPrcnt
        ///union all
        ///select
        ///&apos;CON&apos; as &apos;Origen&apos;
        ///,&apos;&apos; as &apos;Linea&apos;
        ///,&apos;&apos; as &apos;Codigo Retencion&apos;
        ///,0 as &apos;Porcentaje Retencion&apos;
        ///,TaxCode as &apos;Codigo IVA&apos;
        ///,VatPrcnt as &apos;Porcentaje IVA&apos;
        ///,sum(LineTotal - vatsum) as &apos; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string sqlGetCurrentWTandTax {
            get {
                return ResourceManager.GetString("sqlGetCurrentWTandTax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select
        ///&apos;N&apos; as &apos;Selected&apos;
        ///,DocNum
        ///,CardName
        ///,DocDate
        ///,DocTotal
        ///from OINV
        ///where 
        ///	DocEntry not in (select distinct U_DocEntry from [@BYB_T1SWT200] where U_SWTCode=&apos;[--SWTCode--]&apos;) 
        ///and 
        ///	DocEntry not in (Select Distinct BaseEntry as &apos;DocEntry&apos; from RIN1 where BaseEntry is not null and BaseType=13)
        ///and 
        ///	OINV.DocDate &gt;= &apos;[--fromDate--]&apos;
        ///and 
        ///	OINV.DocDate &lt;= &apos;[--toDate--]&apos;
        ///order by DocDate.
        /// </summary>
        internal static string sqlGetMissingSWT {
            get {
                return ResourceManager.GetString("sqlGetMissingSWT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT [DocEntry]
        ///from [@BYB_T1WHT400]
        ///where [U_DocEntry] = [--DocEntry--] and [U_CardCode] = &apos;[--CardCode--]&apos;.
        /// </summary>
        internal static string sqlGetUDODocEntry {
            get {
                return ResourceManager.GetString("sqlGetUDODocEntry", resourceCulture);
            }
        }
    }
}
