//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace T1.B1.WithholdingTax.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class WithholdingTax {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WithholdingTax() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("T1.B1.WithholdingTax.Resources.WithholdingTax", typeof(WithholdingTax).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-16&quot; ?&gt;
        ///&lt;Application&gt;
        ///  &lt;forms&gt;
        ///    &lt;action type=&quot;add&quot;&gt;
        ///      &lt;form appformnumber=&quot;-1&quot; FormType=&quot;-1&quot; type=&quot;0&quot; BorderStyle=&quot;0&quot; uid=&quot;UDO_F_BYB_T1WHTU01_D&quot; title=&quot;Retención por artículo&quot; visible=&quot;1&quot; default_button=&quot;&quot; pane=&quot;0&quot; color=&quot;0&quot; left=&quot;370&quot; top=&quot;127&quot; width=&quot;600&quot; height=&quot;373&quot; client_width=&quot;584&quot; client_height=&quot;334&quot; AutoManaged=&quot;1&quot; SupportedModes=&quot;15&quot; ObjectType=&quot;BYB_T1WHTU01&quot; mode=&quot;3&quot;&gt;
        ///        &lt;datasources&gt;
        ///          &lt;dbdatasources&gt;
        ///            &lt;action type=&quot;add&quot;&gt;
        ///  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string WHTFRM001 {
            get {
                return ResourceManager.GetString("WHTFRM001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-16&quot;?&gt;
        ///&lt;Application&gt;
        ///  &lt;forms&gt;
        ///    &lt;action type=&quot;add&quot;&gt;
        ///      &lt;form appformnumber=&quot;-1&quot; FormType=&quot;-1&quot; type=&quot;4&quot; BorderStyle=&quot;4&quot; uid=&quot;UDO_F_BYB_T1WHTU01_D&quot; title=&quot;Retención de Impuestos&quot; visible=&quot;1&quot; default_button=&quot;&quot; pane=&quot;0&quot; color=&quot;0&quot; left=&quot;370&quot; top=&quot;127&quot; width=&quot;611&quot; height=&quot;454&quot; client_width=&quot;584&quot; client_height=&quot;334&quot; AutoManaged=&quot;1&quot; SupportedModes=&quot;15&quot; mode=&quot;3&quot;&gt;
        ///        &lt;datasources&gt;
        ///          &lt;DataTables&gt;
        ///            &lt;DataTable Uid=&quot;DT_WHT&quot;&gt;
        ///              &lt;Columns&gt;
        ///  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string WHTFRM002 {
            get {
                return ResourceManager.GetString("WHTFRM002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-16&quot; ?&gt;&lt;Application&gt;&lt;forms&gt;&lt;action type=&quot;add&quot;&gt;&lt;form appformnumber=&quot;-1&quot; FormType=&quot;-1&quot; type=&quot;0&quot; BorderStyle=&quot;0&quot; uid=&quot;UDO_F_BYB_T1SWTU001_D&quot; title=&quot;Autoretencion&quot; visible=&quot;1&quot; default_button=&quot;&quot; pane=&quot;0&quot; color=&quot;0&quot; left=&quot;430&quot; top=&quot;257&quot; width=&quot;600&quot; height=&quot;419&quot; client_width=&quot;584&quot; client_height=&quot;380&quot; AutoManaged=&quot;1&quot; SupportedModes=&quot;15&quot; ObjectType=&quot;BYB_T1SWTU001&quot; mode=&quot;3&quot;&gt;&lt;datasources&gt;&lt;dbdatasources&gt;&lt;action type=&quot;add&quot;&gt;&lt;datasource tablename=&quot;@BYB_T1SWT100&quot;/&gt;&lt;datasource tablename=&quot;@BYB [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string WHTFRM003 {
            get {
                return ResourceManager.GetString("WHTFRM003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-16&quot; ?&gt;
        ///&lt;Application&gt;
        ///  &lt;forms&gt;
        ///    &lt;action type=&quot;add&quot;&gt;
        ///      &lt;form appformnumber=&quot;-1&quot; FormType=&quot;-1&quot; type=&quot;0&quot; BorderStyle=&quot;0&quot; uid=&quot;SBOFormEditor_11&quot; title=&quot;Gestión de Autoretenciones&quot; visible=&quot;1&quot; default_button=&quot;&quot; pane=&quot;0&quot; color=&quot;0&quot; left=&quot;598&quot; top=&quot;197&quot; width=&quot;508&quot; height=&quot;337&quot; client_width=&quot;492&quot; client_height=&quot;298&quot; AutoManaged=&quot;0&quot; SupportedModes=&quot;15&quot; ObjectType=&quot;&quot; mode=&quot;1&quot;&gt;
        ///        &lt;datasources&gt;
        ///          &lt;dbdatasources&gt;
        ///            &lt;action type=&quot;add&quot;/&gt;
        ///          &lt;/ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string WHTFRM004 {
            get {
                return ResourceManager.GetString("WHTFRM004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-16&quot; ?&gt;&lt;Application&gt;&lt;forms&gt;&lt;action type=&quot;add&quot;&gt;&lt;form appformnumber=&quot;-1&quot; FormType=&quot;-1&quot; type=&quot;0&quot; BorderStyle=&quot;0&quot; uid=&quot;SBOFormEditor_11&quot; title=&quot;Ajustar Impuestos y Retenciones&quot; visible=&quot;1&quot; default_button=&quot;&quot; pane=&quot;0&quot; color=&quot;0&quot; left=&quot;375&quot; top=&quot;63&quot; width=&quot;518&quot; height=&quot;411&quot; client_width=&quot;502&quot; client_height=&quot;372&quot; AutoManaged=&quot;0&quot; SupportedModes=&quot;15&quot; ObjectType=&quot;&quot; mode=&quot;1&quot;&gt;&lt;datasources&gt;&lt;dbdatasources&gt;&lt;action type=&quot;add&quot;/&gt;&lt;/dbdatasources&gt;&lt;userdatasources&gt;&lt;action type=&quot;add&quot;&gt;&lt;datasource ui [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string WHTFRM005 {
            get {
                return ResourceManager.GetString("WHTFRM005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-16&quot; ?&gt;&lt;Application&gt;&lt;forms&gt;&lt;action type=&quot;add&quot;&gt;&lt;form appformnumber=&quot;-1&quot; FormType=&quot;-1&quot; type=&quot;0&quot; BorderStyle=&quot;0&quot; uid=&quot;SBOFormEditor_11&quot; title=&quot;Validacion de Retenciones&quot; visible=&quot;1&quot; default_button=&quot;&quot; pane=&quot;0&quot; color=&quot;0&quot; left=&quot;339&quot; top=&quot;102&quot; width=&quot;535&quot; height=&quot;169&quot; client_width=&quot;519&quot; client_height=&quot;130&quot; AutoManaged=&quot;0&quot; SupportedModes=&quot;15&quot; ObjectType=&quot;&quot;&gt;&lt;datasources&gt;&lt;dbdatasources&gt;&lt;action type=&quot;add&quot;/&gt;&lt;/dbdatasources&gt;&lt;userdatasources&gt;&lt;action type=&quot;add&quot;/&gt;&lt;/userdatasources&gt;&lt;/datasou [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string WHTFRM006 {
            get {
                return ResourceManager.GetString("WHTFRM006", resourceCulture);
            }
        }
    }
}
