//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace T1.B1.xxxInventoryImpairment.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class sqlQueries {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal sqlQueries() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("T1.B1.xxxInventoryImpairment.Resources.sqlQueries", typeof(sqlQueries).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select
        ///OITM.ItemCode as [Código Artículo], 
        ///OITM.ItemName as [Nombre Artículo],
        ///OITM.AvgPrice as [Precio Estandar],
        ///OITM.OnHand as [Stock General],
        ///OITB.ItmsGrpNam as [Grupo Artículo],
        ///OITW.WhsCode as [Código Almacen],
        ///OWHS.WhsName as [Nombre Almacén],
        ///&apos;N&apos;as Checked, 
        ///OITW.AvgPrice as [Precio en Almacén],
        ///OITW.OnHand as [Stock Almacén],
        ///0.0 as [Det. x Art.],
        ///0.0 as [Total]
        ///from OITM
        ///inner join oitb on oitb.ItmsGrpCod = oitm.ItmsGrpCod inner join OITW on
        ///oitw.ItemCode = oitm.ItemCode inner joi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string sql0001 {
            get {
                return ResourceManager.GetString("sql0001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and 
        ///OITM.ItemCode {0}= &apos;{1}&apos;.
        /// </summary>
        internal static string sql0002 {
            get {
                return ResourceManager.GetString("sql0002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and 
        ///OITM.ItemCode &lt;= &apos;{0}&apos;.
        /// </summary>
        internal static string sql0003 {
            get {
                return ResourceManager.GetString("sql0003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and
        ///OITM.ItmsGrpCod = &apos;{0}&apos;
        ///.
        /// </summary>
        internal static string sql0004 {
            get {
                return ResourceManager.GetString("sql0004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and
        ///OITW.WhsCode {0}= &apos;{1}&apos;.
        /// </summary>
        internal static string sql0005 {
            get {
                return ResourceManager.GetString("sql0005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and
        ///OITW.WhsCode &lt;= &apos;{0}&apos;.
        /// </summary>
        internal static string sql0006 {
            get {
                return ResourceManager.GetString("sql0006", resourceCulture);
            }
        }
    }
}
