//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace T1.B1.Expenses {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class InteractionId : global::System.Configuration.ApplicationSettingsBase {
        
        private static InteractionId defaultInstance = ((InteractionId)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new InteractionId())));
        
        public static InteractionId Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("BYBMEX01")]
        public string T1ExpensesMainMenuId {
            get {
                return ((string)(this["T1ExpensesMainMenuId"]));
            }
            set {
                this["T1ExpensesMainMenuId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("BYBMEX02")]
        public string T1ExpensesConceptsMenuId {
            get {
                return ((string)(this["T1ExpensesConceptsMenuId"]));
            }
            set {
                this["T1ExpensesConceptsMenuId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("BYBMEX03")]
        public string T1ExpensesExpenseTypeMenuId {
            get {
                return ((string)(this["T1ExpensesExpenseTypeMenuId"]));
            }
            set {
                this["T1ExpensesExpenseTypeMenuId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("BYBMEX04")]
        public string T1ExpensesConfigurationMenuId {
            get {
                return ((string)(this["T1ExpensesConfigurationMenuId"]));
            }
            set {
                this["T1ExpensesConfigurationMenuId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("BYBMEX05")]
        public string T1ExpensesRequestMenuId {
            get {
                return ((string)(this["T1ExpensesRequestMenuId"]));
            }
            set {
                this["T1ExpensesRequestMenuId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("BYBMEX06")]
        public string T1ExpensesReportMenuId {
            get {
                return ((string)(this["T1ExpensesReportMenuId"]));
            }
            set {
                this["T1ExpensesReportMenuId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("BYBMEX04")]
        public string T1ExpensesConceptsParentMenuId {
            get {
                return ((string)(this["T1ExpensesConceptsParentMenuId"]));
            }
            set {
                this["T1ExpensesConceptsParentMenuId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("BYBMEX04")]
        public string T1ExpensesExpenseTypeParentMenuId {
            get {
                return ((string)(this["T1ExpensesExpenseTypeParentMenuId"]));
            }
            set {
                this["T1ExpensesExpenseTypeParentMenuId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("BYBMEX01")]
        public string T1ExpensesConfigurationParentMenuId {
            get {
                return ((string)(this["T1ExpensesConfigurationParentMenuId"]));
            }
            set {
                this["T1ExpensesConfigurationParentMenuId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("BYBMEX01")]
        public string T1ExpensesRequestParentMenuId {
            get {
                return ((string)(this["T1ExpensesRequestParentMenuId"]));
            }
            set {
                this["T1ExpensesRequestParentMenuId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("BYBMEX01")]
        public string T1ExpensesReportParentMenuId {
            get {
                return ((string)(this["T1ExpensesReportParentMenuId"]));
            }
            set {
                this["T1ExpensesReportParentMenuId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("BYBMS01")]
        public string T1ExpensesMainParentMenuId {
            get {
                return ((string)(this["T1ExpensesMainParentMenuId"]));
            }
            set {
                this["T1ExpensesMainParentMenuId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("T1LG")]
        public string T1ExpensesTransactionCode {
            get {
                return ((string)(this["T1ExpensesTransactionCode"]));
            }
            set {
                this["T1ExpensesTransactionCode"] = value;
            }
        }
    }
}
