//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace T1.B1.Expenses {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class LocalizationStrings : global::System.Configuration.ApplicationSettingsBase {
        
        private static LocalizationStrings defaultInstance = ((LocalizationStrings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new LocalizationStrings())));
        
        public static LocalizationStrings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Legalizaciones")]
        public string T1ExpensesMainMenuString {
            get {
                return ((string)(this["T1ExpensesMainMenuString"]));
            }
            set {
                this["T1ExpensesMainMenuString"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Conceptos")]
        public string T1ExpensesConceptsMenuString {
            get {
                return ((string)(this["T1ExpensesConceptsMenuString"]));
            }
            set {
                this["T1ExpensesConceptsMenuString"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Tipos de Legalización")]
        public string T1ExpensesExpenseTypeMenuString {
            get {
                return ((string)(this["T1ExpensesExpenseTypeMenuString"]));
            }
            set {
                this["T1ExpensesExpenseTypeMenuString"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Configuración")]
        public string T1ExpensesConfigurationMenuString {
            get {
                return ((string)(this["T1ExpensesConfigurationMenuString"]));
            }
            set {
                this["T1ExpensesConfigurationMenuString"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Solicitud de Legalización")]
        public string T1ExpensesRequestMenuString {
            get {
                return ((string)(this["T1ExpensesRequestMenuString"]));
            }
            set {
                this["T1ExpensesRequestMenuString"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Registro de Legalización")]
        public string T1ExpensesReportMenuString {
            get {
                return ((string)(this["T1ExpensesReportMenuString"]));
            }
            set {
                this["T1ExpensesReportMenuString"] = value;
            }
        }
    }
}
