//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace T1.B1.xxxFSNotes {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class CacheItemNames : global::System.Configuration.ApplicationSettingsBase {
        
        private static CacheItemNames defaultInstance = ((CacheItemNames)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new CacheItemNames())));
        
        public static CacheItemNames Default {
            get {
                return defaultInstance;
            }
        }
    }
}
