//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace T1.B1.xxxFSNotes {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class InteractionId : global::System.Configuration.ApplicationSettingsBase {
        
        private static InteractionId defaultInstance = ((InteractionId)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new InteractionId())));
        
        public static InteractionId Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("sapfsn001")]
        public string mnuNotesLoadId {
            get {
                return ((string)(this["mnuNotesLoadId"]));
            }
            set {
                this["mnuNotesLoadId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("13056")]
        public string notesLoadMenuParentId {
            get {
                return ((string)(this["notesLoadMenuParentId"]));
            }
            set {
                this["notesLoadMenuParentId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("sapfsn002")]
        public string fsNotesMainFormId {
            get {
                return ((string)(this["fsNotesMainFormId"]));
            }
            set {
                this["fsNotesMainFormId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SAP_FSN001")]
        public string fsNotesFormType {
            get {
                return ((string)(this["fsNotesFormType"]));
            }
            set {
                this["fsNotesFormType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SAPNFS")]
        public string fsNotesUDOName {
            get {
                return ((string)(this["fsNotesUDOName"]));
            }
            set {
                this["fsNotesUDOName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<ValidValue value=\"{0}\" description=\"{1}\" />")]
        public string fsValidValuesString {
            get {
                return ((string)(this["fsValidValuesString"]));
            }
            set {
                this["fsValidValuesString"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/Metadata/Tables/item")]
        public string mdTablePath {
            get {
                return ((string)(this["mdTablePath"]));
            }
            set {
                this["mdTablePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/Metadata/UserFields/item")]
        public string mdUserFieldsPath {
            get {
                return ((string)(this["mdUserFieldsPath"]));
            }
            set {
                this["mdUserFieldsPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/Metadata/UDO/item")]
        public string mdUDOPath {
            get {
                return ((string)(this["mdUDOPath"]));
            }
            set {
                this["mdUDOPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("FSNotes")]
        public string configModuleCode {
            get {
                return ((string)(this["configModuleCode"]));
            }
            set {
                this["configModuleCode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("name")]
        public string crReportTypeNameAttribute {
            get {
                return ((string)(this["crReportTypeNameAttribute"]));
            }
            set {
                this["crReportTypeNameAttribute"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("formId")]
        public string crReportFormIdAttribute {
            get {
                return ((string)(this["crReportFormIdAttribute"]));
            }
            set {
                this["crReportFormIdAttribute"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Financial Statements Notes")]
        public string configModuleName {
            get {
                return ((string)(this["configModuleName"]));
            }
            set {
                this["configModuleName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.1.0.2")]
        public string configModuleVersion {
            get {
                return ((string)(this["configModuleVersion"]));
            }
            set {
                this["configModuleVersion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("name")]
        public string crReportNameAttribute {
            get {
                return ((string)(this["crReportNameAttribute"]));
            }
            set {
                this["crReportNameAttribute"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("file")]
        public string crReportPathAttribute {
            get {
                return ((string)(this["crReportPathAttribute"]));
            }
            set {
                this["crReportPathAttribute"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("cmbType")]
        public string formTypeCmbId {
            get {
                return ((string)(this["formTypeCmbId"]));
            }
            set {
                this["formTypeCmbId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Example Note")]
        public string formTypeCmbSelectedValue_1 {
            get {
                return ((string)(this["formTypeCmbSelectedValue_1"]));
            }
            set {
                this["formTypeCmbSelectedValue_1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Custom Note")]
        public string formTypeCmbSelectedValue_2 {
            get {
                return ((string)(this["formTypeCmbSelectedValue_2"]));
            }
            set {
                this["formTypeCmbSelectedValue_2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("formTypeCmbSelectedValue_")]
        public string formTypeCmbSelecterdBase {
            get {
                return ((string)(this["formTypeCmbSelecterdBase"]));
            }
            set {
                this["formTypeCmbSelecterdBase"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/VersionControl/Module[./AdminInfo/Code/text()=\'{0}\']/Installation/Report/Item[@n" +
            "ame=\'{1}\']")]
        public string configReportNodePath {
            get {
                return ((string)(this["configReportNodePath"]));
            }
            set {
                this["configReportNodePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("code")]
        public string configReportCodeAttribute {
            get {
                return ((string)(this["configReportCodeAttribute"]));
            }
            set {
                this["configReportCodeAttribute"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("cmbNotes")]
        public string formTypeCmbNote {
            get {
                return ((string)(this["formTypeCmbNote"]));
            }
            set {
                this["formTypeCmbNote"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("typeCode")]
        public string configReportTypeAttribute {
            get {
                return ((string)(this["configReportTypeAttribute"]));
            }
            set {
                this["configReportTypeAttribute"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("btnGet")]
        public string formButtonGetId {
            get {
                return ((string)(this["formButtonGetId"]));
            }
            set {
                this["formButtonGetId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("519")]
        public string formPreviewMenuId {
            get {
                return ((string)(this["formPreviewMenuId"]));
            }
            set {
                this["formPreviewMenuId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("txtCustom")]
        public string formCusomtTextId {
            get {
                return ((string)(this["formCusomtTextId"]));
            }
            set {
                this["formCusomtTextId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("btnUpdate")]
        public string formButtonUpdateId {
            get {
                return ((string)(this["formButtonUpdateId"]));
            }
            set {
                this["formButtonUpdateId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("UD_Custom")]
        public string formCustomTextDS {
            get {
                return ((string)(this["formCustomTextDS"]));
            }
            set {
                this["formCustomTextDS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("UD_NId")]
        public string formNoteNumberDS {
            get {
                return ((string)(this["formNoteNumberDS"]));
            }
            set {
                this["formNoteNumberDS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("UD_Ntype")]
        public string formTypeDS {
            get {
                return ((string)(this["formTypeDS"]));
            }
            set {
                this["formTypeDS"] = value;
            }
        }
    }
}
