//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace T1.B1.Expenses.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Expenses {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Expenses() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("T1.B1.Expenses.Resources.Expenses", typeof(Expenses).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-16&quot; ?&gt;&lt;Application&gt;&lt;forms&gt;&lt;action type=&quot;add&quot;&gt;&lt;form appformnumber=&quot;-1&quot; FormType=&quot;-1&quot; type=&quot;0&quot; BorderStyle=&quot;0&quot; uid=&quot;UDO_F_BYB_T1EXPU001_D&quot; title=&quot;Conceptos&quot; visible=&quot;1&quot; default_button=&quot;&quot; pane=&quot;1&quot; color=&quot;0&quot; left=&quot;370&quot; top=&quot;127&quot; width=&quot;600&quot; height=&quot;402&quot; client_width=&quot;584&quot; client_height=&quot;363&quot; AutoManaged=&quot;1&quot; SupportedModes=&quot;15&quot; ObjectType=&quot;BYB_T1EXPU001&quot; mode=&quot;3&quot;&gt;&lt;datasources&gt;&lt;dbdatasources&gt;&lt;action type=&quot;add&quot;&gt;&lt;datasource tablename=&quot;@BYB_T1EXP100&quot;/&gt;&lt;datasource tablename=&quot;@BYB_T1E [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BYBEXPF001 {
            get {
                return ResourceManager.GetString("BYBEXPF001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-16&quot; ?&gt;&lt;Application&gt;&lt;forms&gt;&lt;action type=&quot;add&quot;&gt;&lt;form appformnumber=&quot;-1&quot; FormType=&quot;-1&quot; type=&quot;0&quot; BorderStyle=&quot;0&quot; uid=&quot;UDO_F_BYB_T1EXPU002_D&quot; title=&quot;Definición Legalizaciones&quot; visible=&quot;1&quot; default_button=&quot;&quot; pane=&quot;0&quot; color=&quot;0&quot; left=&quot;370&quot; top=&quot;127&quot; width=&quot;600&quot; height=&quot;160&quot; client_width=&quot;584&quot; client_height=&quot;121&quot; AutoManaged=&quot;1&quot; SupportedModes=&quot;15&quot; ObjectType=&quot;BYB_T1EXPU002&quot; mode=&quot;3&quot;&gt;&lt;datasources&gt;&lt;dbdatasources&gt;&lt;action type=&quot;add&quot;&gt;&lt;datasource tablename=&quot;@BYB_T1EXP200&quot;/&gt;&lt;/action&gt;&lt;/dbda [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BYBEXPF002 {
            get {
                return ResourceManager.GetString("BYBEXPF002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-16&quot; ?&gt;&lt;Application&gt;&lt;forms&gt;&lt;action type=&quot;add&quot;&gt;&lt;form appformnumber=&quot;-1&quot; FormType=&quot;-1&quot; type=&quot;0&quot; BorderStyle=&quot;0&quot; uid=&quot;UDO_F_BYB_T1EXPU003_D&quot; title=&quot;Solicitud de Legalización&quot; visible=&quot;1&quot; default_button=&quot;&quot; pane=&quot;0&quot; color=&quot;0&quot; left=&quot;370&quot; top=&quot;127&quot; width=&quot;600&quot; height=&quot;175&quot; client_width=&quot;584&quot; client_height=&quot;136&quot; AutoManaged=&quot;1&quot; SupportedModes=&quot;15&quot; ObjectType=&quot;BYB_T1EXPU003&quot; mode=&quot;3&quot;&gt;&lt;datasources&gt;&lt;dbdatasources&gt;&lt;action type=&quot;add&quot;&gt;&lt;datasource tablename=&quot;@BYB_T1EXP300&quot;/&gt;&lt;/action&gt;&lt;/dbda [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BYBEXPF003 {
            get {
                return ResourceManager.GetString("BYBEXPF003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-16&quot; ?&gt;&lt;Application&gt;&lt;forms&gt;&lt;action type=&quot;add&quot;&gt;&lt;form appformnumber=&quot;-1&quot; FormType=&quot;-1&quot; type=&quot;0&quot; BorderStyle=&quot;0&quot; uid=&quot;UDO_F_BYB_T1EXPU004_D&quot; title=&quot;Legalización&quot; visible=&quot;1&quot; default_button=&quot;&quot; pane=&quot;1&quot; color=&quot;0&quot; left=&quot;509&quot; top=&quot;107&quot; width=&quot;600&quot; height=&quot;387&quot; client_width=&quot;584&quot; client_height=&quot;348&quot; AutoManaged=&quot;1&quot; SupportedModes=&quot;15&quot; ObjectType=&quot;BYB_T1EXPU004&quot; mode=&quot;3&quot;&gt;&lt;datasources&gt;&lt;dbdatasources&gt;&lt;action type=&quot;add&quot;&gt;&lt;datasource tablename=&quot;@BYB_T1EXP400&quot;/&gt;&lt;datasource tablename=&quot;@BYB_ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BYBEXPF004 {
            get {
                return ResourceManager.GetString("BYBEXPF004", resourceCulture);
            }
        }
    }
}
