//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace T1.Classes {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class CacheItemNames : global::System.Configuration.ApplicationSettingsBase {
        
        private static CacheItemNames defaultInstance = ((CacheItemNames)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new CacheItemNames())));
        
        public static CacheItemNames Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("currentVersion")]
        public string currentVersion {
            get {
                return ((string)(this["currentVersion"]));
            }
            set {
                this["currentVersion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("installationInfo")]
        public string installationInfo {
            get {
                return ((string)(this["installationInfo"]));
            }
            set {
                this["installationInfo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("decimals")]
        public string decimals {
            get {
                return ((string)(this["decimals"]));
            }
            set {
                this["decimals"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("thousands")]
        public string thousands {
            get {
                return ((string)(this["thousands"]));
            }
            set {
                this["thousands"] = value;
            }
        }
    }
}
