//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace T1.Settings {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class MainQueries : global::System.Configuration.ApplicationSettingsBase {
        
        private static MainQueries defaultInstance = ((MainQueries)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new MainQueries())));
        
        public static MainQueries Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("select U_ControlXML from [@SAPIFRS] where Code=\'Main\'")]
        public string getControlXMLSQL {
            get {
                return ((string)(this["getControlXMLSQL"]));
            }
            set {
                this["getControlXMLSQL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("select \"U_ControlXML\" from \"@SAPIFRS\" where Code=\'Main\'")]
        public string getControlXMLHANA {
            get {
                return ((string)(this["getControlXMLHANA"]));
            }
            set {
                this["getControlXMLHANA"] = value;
            }
        }
    }
}
