//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace T1.B1.xxxFixedAssets {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class InteractionId : global::System.Configuration.ApplicationSettingsBase {
        
        private static InteractionId defaultInstance = ((InteractionId)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new InteractionId())));
        
        public static InteractionId Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1473000075")]
        public string fixedAssetsMasterFormId {
            get {
                return ((string)(this["fixedAssetsMasterFormId"]));
            }
            set {
                this["fixedAssetsMasterFormId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("sapmnu001")]
        public string fixedAssetsActivateMenuId {
            get {
                return ((string)(this["fixedAssetsActivateMenuId"]));
            }
            set {
                this["fixedAssetsActivateMenuId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5888")]
        public string fixedAssetsActivateMenuParentId {
            get {
                return ((string)(this["fixedAssetsActivateMenuParentId"]));
            }
            set {
                this["fixedAssetsActivateMenuParentId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SAP_FA01")]
        public string productionUnitsFormType {
            get {
                return ((string)(this["productionUnitsFormType"]));
            }
            set {
                this["productionUnitsFormType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("sapmnu002")]
        public string fixedAssetsAddRowMenuId {
            get {
                return ((string)(this["fixedAssetsAddRowMenuId"]));
            }
            set {
                this["fixedAssetsAddRowMenuId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/Metadata/Tables/item")]
        public string mdTablePath {
            get {
                return ((string)(this["mdTablePath"]));
            }
            set {
                this["mdTablePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/Metadata/UserFields/item")]
        public string mdUserFieldsPath {
            get {
                return ((string)(this["mdUserFieldsPath"]));
            }
            set {
                this["mdUserFieldsPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/Metadata/UDO/item")]
        public string mdUDOPath {
            get {
                return ((string)(this["mdUDOPath"]));
            }
            set {
                this["mdUDOPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Item_9")]
        public string fixedAssetsMasterFormMatrixId {
            get {
                return ((string)(this["fixedAssetsMasterFormMatrixId"]));
            }
            set {
                this["fixedAssetsMasterFormMatrixId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Col_1")]
        public string fixedAssetsPUColumnId {
            get {
                return ((string)(this["fixedAssetsPUColumnId"]));
            }
            set {
                this["fixedAssetsPUColumnId"] = value;
            }
        }
    }
}
