//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace T1.B1.xxxFixedAssets {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class LocalizationStrings : global::System.Configuration.ApplicationSettingsBase {
        
        private static LocalizationStrings defaultInstance = ((LocalizationStrings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new LocalizationStrings())));
        
        public static LocalizationStrings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Unidades de Producción")]
        public string FixedAssetsActivateMenuString {
            get {
                return ((string)(this["FixedAssetsActivateMenuString"]));
            }
            set {
                this["FixedAssetsActivateMenuString"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Agregar Linea")]
        public string fixedAssetsAddRowMenuString {
            get {
                return ((string)(this["fixedAssetsAddRowMenuString"]));
            }
            set {
                this["fixedAssetsAddRowMenuString"] = value;
            }
        }
    }
}
