//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace T1.B1.WithholdingTax.Report {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class InteractionId : global::System.Configuration.ApplicationSettingsBase {
        
        private static InteractionId defaultInstance = ((InteractionId)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new InteractionId())));
        
        public static InteractionId Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("bybC0101")]
        public string mnuWHTReportId {
            get {
                return ((string)(this["mnuWHTReportId"]));
            }
            set {
                this["mnuWHTReportId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("bybC0102")]
        public string frmWHTReportFormTypeEx {
            get {
                return ((string)(this["frmWHTReportFormTypeEx"]));
            }
            set {
                this["frmWHTReportFormTypeEx"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("BYBC01")]
        public string InternalClassId {
            get {
                return ((string)(this["InternalClassId"]));
            }
            set {
                this["InternalClassId"] = value;
            }
        }
    }
}
