//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace T1.Classes.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Helpers {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Helpers() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("T1.Classes.Resources.Helpers", typeof(Helpers).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;VersionControl&gt;
        ///    &lt;Module&gt;
        ///        &lt;AdminInfo&gt;
        ///            &lt;Code&gt;&lt;/Code&gt;
        ///            &lt;Name&gt;&lt;/Name&gt;
        ///            &lt;Version&gt;&lt;/Version&gt;
        ///        &lt;/AdminInfo&gt;
        ///        &lt;Installation&gt;
        ///            &lt;UDT&gt;
        ///                &lt;Item name=&quot;&quot; status=&quot;&quot;&gt;
        ///                    
        ///                &lt;/Item&gt;
        ///            &lt;/UDT&gt;
        ///            &lt;UDF&gt;
        ///                &lt;Item name=&quot;&quot; status=&quot;&quot;&gt;&lt;/Item&gt;
        ///                &lt;Item name=&quot;&quot; status=&quot;&quot;&gt;&lt;/Item&gt;
        ///                &lt;Item name=&quot;&quot; status=&quot;&quot;&gt;&lt;/Item&gt;
        ///           [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string VersionControl {
            get {
                return ResourceManager.GetString("VersionControl", resourceCulture);
            }
        }
    }
}
