//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace T1.Classes.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MetaDataResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MetaDataResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("T1.Classes.Resources.MetaDataResources", typeof(MetaDataResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;Metadata&gt;
        ///  &lt;Tables&gt;
        ///    &lt;item name=&quot;BYB_T1RPA100&quot;&gt;
        ///      &lt;BOM&gt;
        ///        &lt;BO&gt;
        ///          &lt;AdmInfo&gt;
        ///            &lt;Object&gt;153&lt;/Object&gt;
        ///            &lt;Version&gt;2&lt;/Version&gt;
        ///          &lt;/AdmInfo&gt;
        ///          &lt;UserTablesMD&gt;
        ///            &lt;row&gt;
        ///              &lt;TableName&gt;BYB_T1RPA100&lt;/TableName&gt;
        ///              &lt;TableDescription&gt;T1 Rel. Party&lt;/TableDescription&gt;
        ///              &lt;TableType&gt;bott_MasterData&lt;/TableType&gt;
        ///              &lt;Archivable&gt;tNO&lt;/Archivable&gt;
        ///            &lt;/row [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MDT1 {
            get {
                return ResourceManager.GetString("MDT1", resourceCulture);
            }
        }
    }
}
