//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace T1.B1.WithholdingTax.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("T1.B1.WithholdingTax.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;Application&gt;
        ///  &lt;forms&gt;
        ///    &lt;action type=&quot;update&quot;&gt;
        ///      &lt;form uid=&quot;&quot; left=&quot;468&quot; top=&quot;240&quot; width=&quot;694&quot; height=&quot;638&quot; client_width=&quot;678&quot; client_height=&quot;599&quot;&gt;
        ///        &lt;datasources&gt;
        ///          &lt;DataTables&gt;
        ///            &lt;action type=&quot;add&quot; /&gt;
        ///          &lt;/DataTables&gt;
        ///          &lt;dbdatasources&gt;
        ///            &lt;action type=&quot;add&quot; /&gt;
        ///          &lt;/dbdatasources&gt;
        ///          &lt;userdatasources&gt;
        ///            &lt;action type=&quot;add&quot;&gt;
        ///              &lt;datasource type=&quot;9&quot; size=&quot;8&quot; uid=&quot;BYB_ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string autoretenciones {
            get {
                return ResourceManager.GetString("autoretenciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Menu String=&quot;Autoretenciones&quot; Enabled=&quot;1&quot; Position=&quot;1&quot; Checked=&quot;0&quot; FatherUID=&quot;BYB_M001&quot; Image=&quot;&quot; Type=&quot;2&quot; UniqueID=&quot;BYB_M002&quot;/&gt;
        ///&lt;Menu String=&quot;Configuración&quot; Enabled=&quot;1&quot; Position=&quot;1&quot; Checked=&quot;0&quot; FatherUID=&quot;BYB_M002&quot; Image=&quot;&quot; Type=&quot;2&quot; UniqueID=&quot;BYB_M003&quot;/&gt;
        ///&lt;Menu String=&quot;Herramientas&quot; Enabled=&quot;1&quot; Position=&quot;2&quot; Checked=&quot;0&quot; FatherUID=&quot;BYB_M002&quot; Image=&quot;&quot; Type=&quot;2&quot; UniqueID=&quot;BYB_M004&quot;/&gt;
        ///&lt;Menu String=&quot;Informes&quot; Enabled=&quot;1&quot; Position=&quot;3&quot; Checked=&quot;0&quot; FatherUID=&quot;BYB_M002&quot; Image=&quot;&quot; Type=&quot;2&quot; UniqueID=&quot;BYB_M005&quot;/&gt;.
        /// </summary>
        internal static string Menu {
            get {
                return ResourceManager.GetString("Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-16&quot;?&gt;
        ///&lt;Application&gt;
        ///  &lt;forms&gt;
        ///    &lt;action type=&quot;add&quot;&gt;
        ///      &lt;form appformnumber=&quot;UDO_FT_BYBT1WHT200&quot; FormType=&quot;UDO_FT_BYBT1WHT200&quot; type=&quot;0&quot; BorderStyle=&quot;0&quot; uid=&quot;UDO_F_BYBT1WHT200&quot; title=&quot;T1 Wtax Config Detail&quot; visible=&quot;1&quot; default_button=&quot;1&quot; pane=&quot;1&quot; color=&quot;0&quot; left=&quot;370&quot; top=&quot;127&quot; width=&quot;600&quot; height=&quot;372&quot; client_width=&quot;&quot; client_height=&quot;&quot; AutoManaged=&quot;1&quot; SupportedModes=&quot;15&quot; ObjectType=&quot;BYBT1WHT200&quot; mode=&quot;3&quot;&gt;
        ///        &lt;datasources&gt;
        ///          &lt;DataTables /&gt;
        ///          &lt;dbd [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string T1_WtaxGeneralConfigDetail {
            get {
                return ResourceManager.GetString("T1_WtaxGeneralConfigDetail", resourceCulture);
            }
        }
    }
}
