//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace T1.B1.Shared {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class LocalizactionStrings : global::System.Configuration.ApplicationSettingsBase {
        
        private static LocalizactionStrings defaultInstance = ((LocalizactionStrings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new LocalizactionStrings())));
        
        public static LocalizactionStrings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("T1")]
        public string T1MainFolderMenuDescription {
            get {
                return ((string)(this["T1MainFolderMenuDescription"]));
            }
            set {
                this["T1MainFolderMenuDescription"] = value;
            }
        }
    }
}
